# Generated by Django 4.2.7 on 2024-01-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='last_attendance_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
