# Generated by Django 4.2.7 on 2024-01-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_student_last_attendance_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance_flag',
            field=models.BooleanField(default=True),
        ),
    ]
