# Generated by Django 4.2.7 on 2024-02-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_student_email_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attendance_flag',
        ),
        migrations.RemoveField(
            model_name='student',
            name='standing',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_attendance',
        ),
    ]
